name: build.yml
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: wgrib2

      - name: build
        run: |
          cd wgrib2
          scripts/build_docker.sh
